Sensorhead twist msg
tu-darmstadt-ros-pkg/hector_teleop pull request #2
Opened 2022-05-20 17:32 UTC by Joschi3

The sensorhead teleop plugin is now able to send either twist or orientation msgs. The behavior by changing the value of the parameter use_twist_msg.

2022-05-23 06:43 UTC, Martin-Oehler commented
Please resolve the conflicts first.

2022-05-24 07:58 UTC, Joschi3 commented
All conflicts are now resolved.

2022-05-24 08:31 UTC, Martin-Oehler requested changes

2022-05-24 08:31 UTC, Martin-Oehler commented on hector_joy_teleop_plugins/config/sensorhead/sensorhead_common.yaml
> +use_twist_command : false
You can enable using the twist command here. It should not have any drawbacks.

2022-05-24 08:31 UTC, Martin-Oehler commented on hector_joy_teleop_plugins/src/sensorhead_teleop.cpp
> +void SensorheadTeleop::publishCommand()
Maybe rename to `publishOrientationCommand` to differentiate it more from `publishTwistCommand`.

2022-05-25 07:20 UTC, merged